### ISSUE TITLE
FieldList rendered as string instead of list

### ISSUE THREAD

**Issue by mschfh** [Vlaaaaaaad/terraform-aws-fargate-samproxy#4]
## Expected Behavior
```toml
FieldList = ["request.method","response.status_code"]
```
## Current Behavior
```toml
FieldList = "['request.method','response.status_code']"
```
## Steps to Reproduce
set a FieldList option in `samproxy_sampler_configs` as suggested in the README:
```hcl
        {
          "name"  = "FieldList"
          "value" = "['request.method','response.status_code']"
        }
```

**Comment by Vlaaaaaaad** [comment]
Hey @mschfh,

Thank you so much for reporting this! 

https://github.com/Vlaaaaaaad/terraform-aws-fargate-samproxy/pull/5 should fix this issue. You can use the new code by upgrading the module version to `v0.0.3`.

Let me know if you still experience issues with lists, and feel free to reopen this issue if so!
